version: "3.5"


services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "9000:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Europe/London"
